#!/usr/bin/env python3
"""
execution/build_earth_data.py
Extracts and simplifies global coastlines from Natural Earth JSON into a compact C header
for Pebble Time 2 3D orthographic globe rendering.
"""

from pathlib import Path
import json

SOURCE_LAND = Path("/Users/danielbally/Git/overpass-watch/watchface/src/pkjs/land.json")
OUTPUT_HEADER = Path(__file__).resolve().parent.parent / "watchface" / "src" / "c" / "earth_land.h"

def simplify_contour(pts, step=7):
    simplified = [pts[i] for i in range(0, len(pts), step)]
    if simplified[-1] != pts[-1]:
        simplified.append(pts[-1])
    return simplified

def main():
    if not SOURCE_LAND.exists():
        raise FileNotFoundError(f"Source land file not found: {SOURCE_LAND}")

    with open(SOURCE_LAND, "r", encoding="utf-8") as f:
        polys = json.load(f)

    # Take the top 8 largest continental landmasses
    major_polys = sorted(polys, key=len, reverse=True)[:8]

    vertices = []
    for poly in major_polys:
        simplified = simplify_contour(poly, step=8)
        for idx, pt in enumerate(simplified):
            lon, lat = pt
            # pen_down = 0 for first point of contour, 1 for subsequent connected points
            pen_down = 0 if idx == 0 else 1
            vertices.append((round(lat), round(lon), pen_down))

    header_content = [
        "// Auto-generated by execution/build_earth_data.py - DO NOT EDIT MANUALLY",
        "#pragma once",
        "#include <pebble.h>",
        "",
        "typedef struct {",
        "  int8_t lat;      // -90 to +90 degrees",
        "  int16_t lon;     // -180 to +180 degrees",
        "  uint8_t pen_down;// 0 = new contour, 1 = connected segment",
        "} EarthVertex;",
        "",
        f"static const uint16_t s_earth_coastline_count = {len(vertices)};",
        "static const EarthVertex s_earth_coastlines[] = {"
    ]

    for lat, lon, pen in vertices:
        header_content.append(f"  {{ {lat:3d}, {lon:4d}, {pen} }},")

    header_content.append("};")
    header_content.append("")

    OUTPUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write("\n".join(header_content))

    print(f"Generated {OUTPUT_HEADER} with {len(vertices)} coastline points.")

if __name__ == "__main__":
    main()
